---
# ====== Application: Tick-It ================================
identification: 
  name: Tick-It
  alias: TICK-IT
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Custom Authentication via TBL_USER # 9113597265221345

authorization: 
  authorization-scheme: MODEL.LOV.MUST_NOT_BE_PUBLIC_USER
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WKSP_IUWORKSPACE

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Tick-It

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 7521124400622754

navigation-bar: 
  implementation: List
  list: Navigation Bar # 7810391671623617
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Tick-It

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 7516193504622732
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 42100313070890

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 7516469597622736
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 42100313070890

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 7516793900622736
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 42100313070890

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 7517006350622737
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 42100313070890

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 7517300272622738
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 42100313070890

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 7517611913622738
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 42100313070890

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 7517955540622739
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 42100313070891

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 7518219137622740
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 42100313070892

- # ====== Component Setting: NATIVE_IR ========================
  id: 7518578220622741
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 42100313070893

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 7518800480622741
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 42100313070894

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 7519121882622742
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 42100313070894

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 7519464131622743
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 42100313070895

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 7519730257622744
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 42100313070896

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 7816519976623673
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 42100313076821

  configuration: 
    build-option: 'Feature: Feedback' # 7813025545623658

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 7816813146623675
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 42100444680584

  configuration: 
    build-option: 'Feature: Access Control' # 7812867510623658

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

